version: '3.1'
services:
  client:
    image: node:latest
    container_name: container_react
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app 
    working_dir: /usr/app
    command: bash -c "npm install && npm start"